language: csharp
solution: src/X.PagedList.sln
sudo: false
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnu build src/X.PagedList.Mvc6/project.json
  - dnu build src/X.PagedList.Mvc6.Example/project.json
